### ISSUE TITLE
comports() failing due to internal 4G module

### ISSUE THREAD

**Issue by lukweb** [pyserial/pyserial#145]
On my notebook I have a builtin 4G module (HP lt4112 Gobi 4G Module) it is using 3 COM ports.

Running: 
from serial.tools.list_ports import comports
comports()

is giving me:
File "C:\Program Files\Python27\lib\site-packages\serial\tools\list_ports_common.py", line 65, in usb_info
    ' LOCATION={}'.format(self.location) if self.location is not None else '')

having a look (and changing) at list_ports_common.py is telling me that pid and vid is None

this works, but might not be very proper:
    def usb_info(self):
        """return a string with USB related information about device"""
        return 'USB VID:PID={}:{}{}{}'.format(
            '{:04X}'.format(self.vid) if self.vid is not None else '',
            '{:04X}'.format(self.pid) if self.pid is not None else '',
            ' SER={}'.format(self.serial_number) if self.serial_number is not None else '',
            ' LOCATION={}'.format(self.location) if self.location is not None else '')

**Comment by jat001** [comment]
Hi. I have the same problem too. But I found the real reason.

A [device instance ID](https://msdn.microsoft.com/en-us/windows/hardware/drivers/install/device-instance-ids) may not have PID, like this.
![snap1](https://cloud.githubusercontent.com/assets/1758850/17394777/7b851702-5a5d-11e6-977a-989e782814f4.png)
So this [regex](https://github.com/pyserial/pyserial/blob/master/serial/tools/list_ports_windows.py#L228) will not work and ```info.vid``` ```info.pid``` is ```None```.

If you want to change ```self.vid``` and ```self.pid``` to prevent this problem. You should use ```self.vid if self.vid is not None else 0``` and ```self.pid if self.pid is not None else 0```.
Otherwise you will get a ValueError ```ValueError: Unknown format code 'X' for object of type 'str'```

**Comment by jat001** [comment]
I wrote a regex and it worked for me. But I do not know if it is a common way or not.
```
VID_([0-9a-f]{4})(?:&PID_([0-9a-f]{4}))?(?:&[a-z]+_[a-z0-9]+)*(?:\\([a-z0-9&]+))?
```

**Comment by zsquareplusc** [comment]
Thank you, both. The regexp now has PID optional and `None` does not generate an error in the `usb_info` function.
