### ISSUE TITLE
read_until: Does not honor timeout

### ISSUE THREAD

**Issue by herm** [pyserial/pyserial#182]
The documentation on the timeout parameter is pretty clear:

```
timeout = x: set timeout to x seconds (float allowed) returns immediately 
when the requested number of bytes are available, otherwise wait until
the timeout expires and return all bytes that were received until then.
```

read_until however does never return if at least one byte is received within each timeout period. e.g. timeout=1 and the device sends 2bytes/second (but no terminator). This is definitely not the expected behavior, as a device sending unexpected data can block your application forever. 

The problem is caused by ``read(1)`` being called repeatedly without checking for the total time taken. https://github.com/pyserial/pyserial/blob/master/serial/serialutil.py#L640

**Comment by herm** [comment]
Thanks for the fix.

**Comment by yuzeni** [comment]
Hello there, just wanted to share my frustration with the _solution_ that was introduced here. The documentation can be interpreted differently in my opinion.
It is reasonable to assume that the timeout should refer only to `read()`, and not to every function that returns bytes from the serialport. Because reading from the serialport is the thing which usually requires timeout control. The quoted text in the original issue even mentions that a specific number of bytes were requested, which is not the case with `read_until()`.

The specific use-case where this becomes troublesome is when `timeout=0`, then you will always get just a single byte when calling `read_until()`. The _correct_ behavior (in my opinion) would be to just never block when `timeout=0`. So keep checking if the terminator is found as long as there are bytes in the buffer, but please don't wait if the buffer is exhausted.

There should be another timeout variable (maybe passed to the function directly) to do the thing this issue requested.
