### ISSUE TITLE
miniterm: Autocompletion bug

### ISSUE THREAD

**Issue by Gim6626** [pyserial/pyserial#291]
Due to some bug autocompletion in bash is not working correctly when I use miniterm, though in minicom it works correctly. For example I want to list root directory subdirectories starting with letter "s", to do it I type in shell "ls s" and then press TAB twice, after it I see "[J" in command line and command line editing is broken - I press backspaces but "ls " still remains in command line:
> / # ls s␛[J
> sbin/   share/  sys/

Could anybody help solving this trouble?

**Comment by zsquareplusc** [comment]
actually, this is intention. miniterm should be a good tool to test and debug serial connections it's not the main goal to be a good terminal program ;-) because of that it filters and replaces escape sequences by default.

`python -m serial.tools.miniterm -f help` gives you a list of filters, you may get happy with `-f direct` or the `--raw` switch, at lest when you run miniterm in a capable terminal.

**Comment by Gim6626** [comment]
`-f direct` worked for me, thanks
