### ISSUE TITLE
Opening twice the same port on raspberry

### ISSUE THREAD

**Issue by aleksbelov** [pyserial/pyserial#378]
Why there is no exception?
![screen shot 2018-08-17 at 23 41 30](https://user-images.githubusercontent.com/4018772/44291105-f5eaf900-a284-11e8-88ae-f9bff143d561.png)

**Comment by Nable80** [comment]
Because it's OK to open any file (including device nodes) multiple times in unix-like systems. There are use-cases for such default behavior. If you need some kind of synchronization, you can use lock-files and locking API (flock/lockf/fnctl-lock).

Why in the world do you expect any exception when you didn't ask for exclusive lock explicitely?

**Comment by zsquareplusc** [comment]
recent pySerial support an [`exclusive` flag](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial) which should trigger an exception in this example.
