### ISSUE TITLE
PySerial does not exit on SIGINT

### ISSUE THREAD

**Issue by timoschwarzer** [pyserial/pyserial#570]
### Description of problem

Sending SIGINT to `python -m serial.tools.miniterm` prints `--- exit ---` but does not actually exit.

#### Steps to reproduce

1. Start a terminal with `python -m serial.tools.miniterm`
2. Find the PID with `ps -aux | grep python` or your system monitor GUI
3. Run `kill -INT <PID>` in another shell

**Comment by timoschwarzer** [comment]
Downstream issue: https://github.com/platformio/platformio-core/issues/3841

**Comment by NickCrews** [comment]
Can easily reproduce on MacOS 11.2.1. Interestingly, sending `SIGINT` twice _does_ kill miniterm.

**Comment by NickCrews** [comment]
After some investigation, the relevant code seems to be in the main entry point:
https://github.com/pyserial/pyserial/blob/0e7634747568547b8a7f9fd0c48ed74f16af4b23/serial/tools/miniterm.py#L1030-L1038.
By default, since we don't have any signal handlers registered, when miniterm receives SIGINT, the default handler is used, which raises a `KeyboardInterrupt`. The first time we receive a SIGINT, we are in the first `miniterm.join(True)` call, and this `KeyboardInterrupt` is caught by the `try` block, and then we happily continue into the second `miniterm.join()`call. Now, if we receive another SIGINT, this time the `KeyboardInterrupt` isn't caught, and now we exit. Note that now the cleanup code of `miniterm.close()` isn't called, so the serial port is never closed.

@timoschwarzer, if you're looking for a short term solution (pyserial doesn't seem to be very consistently maintained), then I would recommend using the `signal` module to register your own custom cleanup code, something like:
```
import signal

def handler(sig, frame):
    do_custom_cleanup()

signal.signal(signal.SIGINT, handler)
```

Longer term, miniterm should actually handle SIGINTs properly and should exit with cleanup upon receiving the first SIGINT. IDK exactly how to do this, since I couldn't quite understand why miniterm does certain things and if they are important (e.g. why are there the two slightly different calls to `miniterm.join()`, one within a `try` block?). I see a few possible options:

1) Register our own SIGINT handler with `signal.signal()`. With some playing around, if the handler calls `miniterm.stop()` then it pretty much works, with another tweak so that we also call `console.cancel()` so that we don't hang waiting for keyboard input.
2) Get rid of the first `try` block, or get rid of one of the two `miniterm.join()` calls. I don't see why they are needed.

@zsquareplusc , do you have any thoughts on this? I could submit some PRs with an OK or guidance.

**Comment by zsquareplusc** [comment]
the try/catch for `KeyboardInterrupt` is to avoid printing tracebacks in the end.

joining one thread first and then both (reader and writer) had a good reason, but i would need to research too...

added an implementation with `signal`

**Comment by joecorsi** [comment]
sorry to comment on a closed issue but this is still an issue. best i can is kill the active terminal in vs code.

**Comment by caschoener** [comment]
Turns out you're supposed to kill pyserial via ctrl + ].  The more you know

**Comment by krischik** [comment]
> Turns out you're supposed to kill pyserial via ctrl + ]. The more you know

But that works only if you have a US keyboard. Everybody else is just stuck in the program and never gets out.
