### ISSUE TITLE
comport name conflicts?

### ISSUE THREAD

**Issue by bactone** [pyserial/pyserial#595]
I am new to pyserial, and i encounter a similar problem with the one in the link:
[https://stackoverflow.com/questions/65288381/python-serial-conflict-between-serial-over-bluetooth-link-and-usb-serial-devic](url)

so i wonder whether we can set the port.device or port.name unique so that we can treat it as the ID of com ports?

**Comment by zsquareplusc** [comment]
it's a "feature" of Windows that you can manually set the COM ports to the same name. It even works fine as long as you only plug in one at a time.

i don't see how or why pySerial should try to fix something here. ports are opened by their "COMx" name so two at once can not be differentiated. i don't think this problem is seen often in the field and it can be resolved by manually assigning an unique COM port number in the Windows device manager.
